name: K6 Performance Tests

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          docker --version

      - name: Install k6
        run: |
          curl -s https://packagecloud.io/install/repositories/loadimpact/k6/script.deb.sh | sudo bash
          sudo apt-get install -y k6
          k6 version
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run k6 performance tests
        run: |
          docker run -i --name k6-tests grafana/k6 run --vus 10 --duration 30s - <script.js

      - name: Extract test results from container
        run: |
          docker cp k6-tests:/home/k6/summary.html ./                            
      
      - name: Upload test results as artifact
        uses: actions/download-artifact@v4
        with:
          name: k6-test-results
          path: ./summary.html
