name: K6 Performance Tests

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  k6-test:
    runs-on: ubuntu-latest

    container:
      image: grafana/k6

    steps:
      - name: Set permissions on temp directory
        run: apt update -y && apt install sudo -y && chmod -R 777 /__w/_temp

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run k6 performance tests
        run: |
          k6 run --vus 10 --duration 30s script.js

      - name: Upload test results as artifact
        uses: actions/download-artifact@v4
        with:
          name: k6-test-results
          path: /home/k6/summary.html
